"""
Home page — IND320 Reservoir Data Analysis.
Sidebar navigation is auto-generated by Streamlit from the pages/ folder.
"""
import streamlit as st
from data_loader import load_data, csv_path

st.set_page_config(
    page_title="Reservoir Data Analysis",
    page_icon="💧",
    layout="wide",
)

st.title("💧 Reservoir Data Analysis")
st.write(
    "This Streamlit application provides an interactive view of the "
    "Norwegian reservoir dataset. Part of the IND320 portfolio."
)

st.sidebar.title("Navigation")
st.sidebar.info("Use the pages above to explore the data and plots.")

st.header("Welcome")
st.write(
    "Use the pages in the sidebar to:\n\n"
    "- **Data Table** — the imported data as a table, one row per column, "
    "with an inline sparkline for the first month.\n"
    "- **Plot** — interactively plot any column, or all numeric columns, "
    "over a chosen month range.\n"
    "- **About** — project description, AI usage and work log."
)

st.subheader("Quick dataset summary")
try:
    df = load_data()
    c1, c2, c3 = st.columns(3)
    c1.metric("Rows", f"{len(df):,}")
    c2.metric("Columns", f"{df.shape[1]}")
    if "date" in df.columns:
        c3.metric(
            "Period",
            f"{df['date'].min().date()} → {df['date'].max().date()}",
        )
    with st.expander("Preview first 5 rows"):
        st.dataframe(df.head(), use_container_width=True)
except FileNotFoundError:
    st.error(f"Could not find reservoirs.csv. Looked here: `{csv_path()}`")

st.subheader("Project links")
st.markdown(
    "- **GitHub repository:** [https://github.com/khalidrashed/NMBU-IND320]"
    "(https://github.com/khalidrashed/NMBU-IND320)\n"
    "- **Streamlit app:** [https://nmbu-ind320-khalid-rashed.streamlit.app/]"
    "(https://nmbu-ind320-khalid-rashed.streamlit.app/)"
)